#!/bin/sh
# Set the tmpfs partition


. /scripts/functions
# break in live-tmpfs
maybe_break live-tmpfs

/bin/loadkeys /etc/console/boottime.kmap.gz >> /tmp/initramfs.debug 2>&1


modprobe -q squashfs >> /tmp/initramfs.debug 2>&1
modprobe -q loop >> /tmp/initramfs.debug 2>&1
modprobe -q aufs >> /tmp/initramfs.debug 2>&1

ln -s /bin/busybox /bin/losetup


mkdir /mnt >> /tmp/initramfs.debug 2>&1
echo "Mounting tmpfs " >> /tmp/initramfs.debug 2>&1
mount -t tmpfs -o "size=80%" tmpfs /mnt >> /tmp/initramfs.debug 2>&1




exit 0
