#!/bin/sh
# 


quiet=n



# Arrange for shells on virtual consoles, rather than login prompts
. /conf/initramfs.conf

# load meta settings
[ -f /.dirs/dev/system/settings.conf ] && . /.dirs/dev/system/settings.conf
USERNAME=${conf_username}

# Avoid empty liveuser
if [  "$USERNAME" = "" ] ; then
 USERNAME=liveuser
fi

# disable root passwd
chroot ${rootmnt}/ usermod -L root



# /etc/crontab remaining disabled, yet also not run by anacron
for file in cryptdisks postfix exim4 checkfs.sh checkroot.sh ntpdate mountall.sh ; do
   if [ -f ${rootmnt}/etc/init.d/${file} ]; then
	echo "moving ${rootmnt}/etc/init.d/${file}..." >> /tmp/initramfs.debug
	mv ${rootmnt}/etc/init.d/${file} ${rootmnt}/etc/init.d/${file}.disabled >> /tmp/initramfs.debug 2>&1
   fi
done

exit 0
